version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install boto3
  build:
    commands:
      - echo Entered the build phase...
      # Zero Padding
      - buildnum=$(printf "%05d" ${CODEBUILD_BUILD_NUMBER})
      - python buildspec/generate_scope_templates.py
      - python buildspec/generate_user_templates.py
      - python buildspec/generate_key_templates.py
  post_build:
    commands:
      - aws s3 sync output/scopes s3://${S3Bucket}/builds/scopes/${buildnum}/
      - aws s3 sync output/users s3://${S3Bucket}/builds/users/${buildnum}/
      - aws s3 sync output/keys s3://${S3Bucket}/builds/keys/${buildnum}/
artifacts:
  files:
    - '**/*'
  discard-paths: no