version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install boto3
  build:
    commands:
      - echo Entered the build phase...
      - python buildspec/generate_pipeline_templates.py
  post_build:
    commands:
      - aws s3 sync generated-pipeline-templates s3://${S3Bucket}/generated-pipeline-templates/ --delete
      - aws s3 sync templates s3://${S3Bucket}/templates/ --delete
artifacts:
  files:
    - '**/*'
  discard-paths: no