version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install boto3
  build:
    commands:
      # Zero Padding
      - buildnum=$(printf "%05d" ${CODEBUILD_BUILD_NUMBER})
      - echo Entered the build phase...
      - python buildspec/generate_main_template.py
  post_build:
    commands:
      - aws s3 sync output/main s3://${S3Bucket}/builds/main/${buildnum}/
artifacts:
  files:
    - '**/*'
  base-directory: 'output/main'
  discard-paths: yes