version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install boto3
  build:
    commands:
      - echo Entered the build phase...
      - mkdir -p generated-main-template
      - python buildspec/generate_main_template.py
artifacts:
  files:
    - '**/*'
  base-directory: 'generated-main-template'
  discard-paths: yes