version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install boto3
  build:
    commands:
      # Zero Padding
      - buildnum=$(printf "%05d" ${CODEBUILD_BUILD_NUMBER})
      - echo Entered the build phase...
      - python buildspec/update_stacks.py